In [167]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

1.0.1.post2
True


In [168]:
from torch import nn
import numpy as np
from torch import nn
import torch.nn.functional as F

In [169]:
import os
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split

In [170]:
seed=4
df=pd.read_csv("../../data/ILD.csv")
no_of_rows,no_of_cols=df.shape
print (no_of_rows,no_of_cols)
df.head()

18144 31


id_ref gen_name       v1       v2       v3       v4       v5  \
0        117_at    HSPA6  9.30153  7.76291  8.22701  6.53772  7.07184   
1  1552256_a_at   SCARB1  9.23851  8.72522  9.64837  8.57190  8.65099   
2  1552264_a_at    MAPK1  7.66847  6.33183  7.63279  6.88978  5.22121   
3    1552266_at   ADAM32  2.93300  3.21916  2.90779  2.92548  3.00375   
4    1552269_at  SPATA17  3.28760  3.28215  3.23187  4.13789  3.28960   

        v6       v7       v8  ...      v20      v21      v22       v23  \
0  6.52416  8.44547  9.12909  ...  7.65737  7.57223  6.32249   8.68267   
1  7.83348  9.23631  7.48586  ...  7.62708  8.58799  8.29108  10.14260   
2  7.19912  6.05334  7.88042  ...  6.59411  6.97608  7.01681   6.22543   
3  2.92548  3.48475  2.90148  ...  2.87648  2.88108  2.88388   3.70028   
4  3.67241  3.32874  3.35934  ...  3.26634  3.26095  3.24001   3.30414   

       v24      v25      v26      v27      v28      v29  
0  7.96583  7.06424  7.83115  7.10093  8.22633  7.02261  
1  8.76561  8.72965  9.03287  8.62517  9.47877  8.99476  
2  7.47331  5.71312  6.74352  6.95748  6.91755  6.51478  
3  2.89574  2.89005  2.80739  2.86702  2.92548  2.96130  
4  3.26701  3.22343  3.18599  3.27333  3.26745  3.29148  

[5 rows x 31 columns]

In [171]:
header_of_pd=['v'+str(i+1) for i in range(no_of_cols-2)]
X=np.array(df[header_of_pd])
print(X.shape)

(18144, 29)


In [172]:
fil=open('../../data/labels_ILD.txt','r')
tmp=list()
for line in fil:
	tmp.append(int(line))

Y=np.array(tmp)


In [173]:
augmented_X=[]
augmented_Y=[]
a=0
b=0
c=0
d=0
choice=0
t=0
for i in Y:
    if i==0:
        
        choice=1
        a=a+choice
    elif i==1:
        choice=2
        b=b+choice
        
    elif i==2:
        choice=4
        c=c+choice
    for u in range(choice):
        augmented_X.append(X[t])
        augmented_Y.append(Y[t])
    t=t+1
    
print(a,b,c,d)
augmented_X=np.array(augmented_X)
augmented_Y=np.array(augmented_Y)

9947 10952 10884 0


In [174]:
X_train,X_test,Y_train,Y_test=train_test_split(augmented_X,augmented_Y,test_size=0.20,random_state=2)
print(X_test.shape)

(6357, 29)


In [175]:
class Net(torch.nn.Module):
    def __init__(self, n_feature,out_features):
        super(Net, self).__init__()
        self.hidden1 = torch.nn.Linear(n_feature,300)
        self.hidden2 = torch.nn.Linear(300,100)
        self.hidden3 = torch.nn.Linear(100,50)
        self.hidden4 = torch.nn.Linear(50,10)
        self.predict = torch.nn.Linear(10,out_features)
        self.bn1 = nn.BatchNorm1d(num_features=300)
        self.bn2 = nn.BatchNorm1d(num_features=100)
        self.bn3 = nn.BatchNorm1d(num_features=50)
        self.bn4 = nn.BatchNorm1d(num_features=10)
        self.dropout=nn.Dropout(0.2)

        
    def forward(self, x):
        x = F.relu(self.hidden1(x))
        x=self.bn1(x)
        x=self.dropout(x)
        x = F.relu(self.hidden2(x))
        x=self.bn2(x)
        x =F.relu(self.hidden3(x))
        x=self.bn3(x)
        x=self.dropout(x)
        x =F.relu(self.hidden4(x))
        x=self.bn4(x)
        x=F.relu(self.predict(x))
        return x
def accurate():
    total = X_test.shape[0]
    x_test=torch.tensor(X_test,dtype=torch.float)
    y_test=torch.tensor(Y_test,dtype=torch.long)
    outputs = MP(x_test)
    _, predicted = torch.max(outputs.data, 1)
    correct = (predicted.cpu() == y_test).sum()
    confusion_matrix = torch.zeros(3, 3)
    print('Accuracy of the network on the test data: %d %%' % (100 * correct / total))
    for t, p in zip(y_test.view(-1), predicted.view(-1)):
        confusion_matrix[t.long(), p.long()] += 1
    print(confusion_matrix)

In [176]:
MP=Net(29,3)

inp=torch.tensor(X_test,dtype=torch.float)

criterion = nn.CrossEntropyLoss()
target=torch.tensor(np.zeros((4)),dtype=torch.long)
#output = criterion(mid, target)

optimizer = torch.optim.Adam(MP.parameters(), lr = 0.0001)

epoch=100
batch=10

sizez=(np.array(X_train)).shape[0]
print (sizez)




25426


In [177]:

epoch=10000
def trainz():
    no_batch=(sizez//batch)
    for i in range (epoch):
        start=0
        NET_LOSS=0
        for j in range(no_batch+1):

            stop=start+batch
            if(stop<=sizez):
                  stop=stop
            else:
                  stop=sizez
        if start>=sizez:
              break

        x_batch=torch.tensor(X_train[start:stop],dtype=torch.float)
        y_batch=torch.tensor(Y_train[start:stop],dtype=torch.long)

        out_batch=MP(x_batch)
        LOSS_BATCH=criterion(out_batch,y_batch)
        optimizer.zero_grad()
        LOSS_BATCH.backward()
        optimizer.step()
        NET_LOSS=NET_LOSS+LOSS_BATCH
#       print(str(LOSS_BATCH)+"___"+str(j))
        start=start+batch
        if start>=sizez or start>stop:
              break
        accurate()
        print(NET_LOSS)

trainz()

Accuracy of the network on the test data: 39 %
tensor([[ 923.,  266.,  767.],
        [ 746.,  137., 1300.],
        [ 676.,   77., 1465.]])
tensor(1.0493, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 40 %
tensor([[ 959.,  270.,  727.],
        [ 730.,  132., 1321.],
        [ 655.,   99., 1464.]])
tensor(1.0629, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 41 %
tensor([[ 987.,  248.,  721.],
        [ 647.,  173., 1363.],
        [ 663.,   78., 1477.]])
tensor(1.0817, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 42 %
tensor([[1057.,  244.,  655.],
        [ 640.,  169., 1374.],
        [ 659.,   79., 1480.]])
tensor(1.0825, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 43 %
tensor([[1102.,  223.,  631.],
        [ 560.,  207., 1416.],
        [ 651.,   82., 1485.]])
tensor(1.0483, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 44 %
tensor([[1140.,  230.,  586.],
        [ 583.,  178.,

Accuracy of the network on the test data: 59 %
tensor([[1629.,   52.,  275.],
        [ 229.,  470., 1484.],
        [ 485.,   60., 1673.]])
tensor(0.9397, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 59 %
tensor([[1632.,   48.,  276.],
        [ 207.,  504., 1472.],
        [ 479.,   72., 1667.]])
tensor(0.8672, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 60 %
tensor([[1633.,   51.,  272.],
        [ 218.,  520., 1445.],
        [ 455.,   59., 1704.]])
tensor(0.9026, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 61 %
tensor([[1655.,   44.,  257.],
        [ 199.,  560., 1424.],
        [ 448.,   63., 1707.]])
tensor(0.9358, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 60 %
tensor([[1612.,   50.,  294.],
        [ 220.,  539., 1424.],
        [ 462.,   77., 1679.]])
tensor(0.9561, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 61 %
tensor([[1646.,   47.,  263.],
        [ 196.,  562.,

Accuracy of the network on the test data: 67 %
tensor([[1733.,   23.,  200.],
        [ 110.,  860., 1213.],
        [ 433.,   56., 1729.]])
tensor(0.7964, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 68 %
tensor([[1700.,   30.,  226.],
        [ 105.,  891., 1187.],
        [ 416.,   49., 1753.]])
tensor(0.8288, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 68 %
tensor([[1692.,   32.,  232.],
        [  97.,  881., 1205.],
        [ 409.,   52., 1757.]])
tensor(0.8408, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 68 %
tensor([[1711.,   24.,  221.],
        [  93.,  905., 1185.],
        [ 412.,   58., 1748.]])
tensor(0.8206, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 69 %
tensor([[1708.,   24.,  224.],
        [  98.,  940., 1145.],
        [ 415.,   43., 1760.]])
tensor(0.8519, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 69 %
tensor([[1726.,   21.,  209.],
        [  91.,  936.,

Accuracy of the network on the test data: 73 %
tensor([[1742.,   13.,  201.],
        [  49., 1124., 1010.],
        [ 361.,   34., 1823.]])
tensor(0.7980, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 73 %
tensor([[1726.,   15.,  215.],
        [  58., 1091., 1034.],
        [ 348.,   44., 1826.]])
tensor(0.7850, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 73 %
tensor([[1742.,   16.,  198.],
        [  69., 1118.,  996.],
        [ 331.,   55., 1832.]])
tensor(0.7772, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 73 %
tensor([[1723.,   22.,  211.],
        [  56., 1084., 1043.],
        [ 324.,   47., 1847.]])
tensor(0.7808, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 73 %
tensor([[1726.,   15.,  215.],
        [  49., 1107., 1027.],
        [ 351.,   43., 1824.]])
tensor(0.8312, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 73 %
tensor([[1731.,   14.,  211.],
        [  61., 1107.,

Accuracy of the network on the test data: 74 %
tensor([[1741.,   10.,  205.],
        [  46., 1180.,  957.],
        [ 323.,   49., 1846.]])
tensor(0.7715, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 75 %
tensor([[1729.,   17.,  210.],
        [  36., 1204.,  943.],
        [ 338.,   39., 1841.]])
tensor(0.7463, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 75 %
tensor([[1743.,   15.,  198.],
        [  50., 1210.,  923.],
        [ 327.,   40., 1851.]])
tensor(0.7536, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 74 %
tensor([[1707.,   18.,  231.],
        [  56., 1188.,  939.],
        [ 335.,   46., 1837.]])
tensor(0.7697, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 75 %
tensor([[1753.,   10.,  193.],
        [  44., 1210.,  929.],
        [ 316.,   40., 1862.]])
tensor(0.7467, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 75 %
tensor([[1742.,   14.,  200.],
        [  58., 1189.,

Accuracy of the network on the test data: 78 %
tensor([[1776.,   15.,  165.],
        [  32., 1327.,  824.],
        [ 314.,   36., 1868.]])
tensor(0.7353, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 78 %
tensor([[1766.,    7.,  183.],
        [  32., 1310.,  841.],
        [ 286.,   44., 1888.]])
tensor(0.7327, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 77 %
tensor([[1766.,   12.,  178.],
        [  37., 1270.,  876.],
        [ 291.,   42., 1885.]])
tensor(0.7389, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 77 %
tensor([[1748.,   11.,  197.],
        [  38., 1284.,  861.],
        [ 304.,   43., 1871.]])
tensor(0.7177, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 77 %
tensor([[1763.,    8.,  185.],
        [  46., 1258.,  879.],
        [ 297.,   40., 1881.]])
tensor(0.7363, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 77 %
tensor([[1753.,   10.,  193.],
        [  37., 1322.,

Accuracy of the network on the test data: 79 %
tensor([[1779.,    7.,  170.],
        [  35., 1384.,  764.],
        [ 291.,   41., 1886.]])
tensor(0.7237, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 78 %
tensor([[1780.,   11.,  165.],
        [  36., 1344.,  803.],
        [ 285.,   45., 1888.]])
tensor(0.7111, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 78 %
tensor([[1775.,    8.,  173.],
        [  43., 1344.,  796.],
        [ 280.,   48., 1890.]])
tensor(0.7154, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 79 %
tensor([[1773.,    5.,  178.],
        [  25., 1368.,  790.],
        [ 274.,   57., 1887.]])
tensor(0.7126, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 79 %
tensor([[1780.,   10.,  166.],
        [  35., 1370.,  778.],
        [ 277.,   46., 1895.]])
tensor(0.7030, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 79 %
tensor([[1772.,   10.,  174.],
        [  30., 1377.,

tensor([[1758.,    7.,  191.],
        [  34., 1401.,  748.],
        [ 261.,   62., 1895.]])
tensor(0.6831, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[1769.,   12.,  175.],
        [  32., 1451.,  700.],
        [ 250.,   70., 1898.]])
tensor(0.6732, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[1778.,    8.,  170.],
        [  25., 1445.,  713.],
        [ 262.,   69., 1887.]])
tensor(0.6899, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 79 %
tensor([[1766.,    6.,  184.],
        [  33., 1440.,  710.],
        [ 260.,   79., 1879.]])
tensor(0.7052, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[1772.,    7.,  177.],
        [  18., 1469.,  696.],
        [ 246.,   76., 1896.]])
tensor(0.7136, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[1776.,    3.,  177.],
        [  26., 1434.,  723.],
        [ 260.,   73., 1885.]])
tensor

tensor([[1743.,    7.,  206.],
        [  30., 1517.,  636.],
        [ 230.,   90., 1898.]])
tensor(0.6626, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[1743.,    7.,  206.],
        [  28., 1540.,  615.],
        [ 227.,   93., 1898.]])
tensor(0.6686, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[1752.,    7.,  197.],
        [  23., 1507.,  653.],
        [ 240.,   88., 1890.]])
tensor(0.6716, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[1754.,    6.,  196.],
        [  31., 1521.,  631.],
        [ 229.,   79., 1910.]])
tensor(0.6490, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[1747.,    8.,  201.],
        [  23., 1515.,  645.],
        [ 245.,   81., 1892.]])
tensor(0.6801, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[1756.,    9.,  191.],
        [  27., 1535.,  621.],
        [ 219.,   79., 1920.]])
tensor

Accuracy of the network on the test data: 82 %
tensor([[1739.,    5.,  212.],
        [  17., 1594.,  572.],
        [ 195.,   82., 1941.]])
tensor(0.6232, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 82 %
tensor([[1736.,    6.,  214.],
        [  23., 1570.,  590.],
        [ 185.,   89., 1944.]])
tensor(0.6275, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 82 %
tensor([[1717.,    7.,  232.],
        [  26., 1581.,  576.],
        [ 191.,   72., 1955.]])
tensor(0.6389, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1739.,    6.,  211.],
        [  21., 1601.,  561.],
        [ 179.,   95., 1944.]])
tensor(0.6493, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 82 %
tensor([[1717.,    7.,  232.],
        [  24., 1584.,  575.],
        [ 200.,   82., 1936.]])
tensor(0.6110, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 82 %
tensor([[1733.,    3.,  220.],
        [  19., 1598.,

Accuracy of the network on the test data: 83 %
tensor([[1711.,    5.,  240.],
        [  22., 1645.,  516.],
        [ 168.,  102., 1948.]])
tensor(0.6001, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1717.,    9.,  230.],
        [  25., 1645.,  513.],
        [ 182.,   78., 1958.]])
tensor(0.6149, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1717.,    4.,  235.],
        [  24., 1650.,  509.],
        [ 174.,   92., 1952.]])
tensor(0.5873, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1703.,    5.,  248.],
        [  20., 1644.,  519.],
        [ 173.,  101., 1944.]])
tensor(0.6139, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1718.,    5.,  233.],
        [  26., 1647.,  510.],
        [ 180.,  102., 1936.]])
tensor(0.6338, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1722.,    4.,  230.],
        [  20., 1635.,

tensor([[1738.,    5.,  213.],
        [  12., 1641.,  530.],
        [ 176.,  116., 1926.]])
tensor(0.5808, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1727.,    5.,  224.],
        [  13., 1627.,  543.],
        [ 186.,   95., 1937.]])
tensor(0.5852, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1699.,    6.,  251.],
        [  17., 1652.,  514.],
        [ 158.,  117., 1943.]])
tensor(0.5919, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1724.,    7.,  225.],
        [  17., 1685.,  481.],
        [ 190.,  109., 1919.]])
tensor(0.5964, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 83 %
tensor([[1713.,    6.,  237.],
        [  15., 1660.,  508.],
        [ 178.,  111., 1929.]])
tensor(0.5806, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 84 %
tensor([[1747.,    6.,  203.],
        [  14., 1651.,  518.],
        [ 159.,  103., 1956.]])
tensor

Accuracy of the network on the test data: 83 %
tensor([[1711.,    3.,  242.],
        [  10., 1683.,  490.],
        [ 170.,  116., 1932.]])
tensor(0.5698, grad_fn=<AddBackward0>)


KeyboardInterrupt: 

In [178]:
torch.save(MP.state_dict(), "MLP_ILD_15.pt")