In [3]:
from os import path

import torch
print(torch.__version__)
print(torch.cuda.is_available())
from torchvision import datasets, transforms
import pandas as pd
import numpy as np
from path import Path
import torch.utils.data as data

from torch import nn
import numpy as np
import pandas as pd
import tqdm

import os
import os
from sklearn.model_selection import train_test_split
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn.functional as F


all_letters="ACTG"

1.0.1.post2
True


In [4]:
def letterToIndex(letter):
    return all_letters.find(letter)
def letterToTensor(letter):
  tensor=torch.zeros(1,4)
  tensor[0][letterToIndex(letter)] = 1
  return tensor
def lineToTensor(line):
  tensor=torch.zeros(len(line),1,4)
  for li,letters in enumerate(line):
    tensor[li][0][letterToIndex(letters)]=1
  return(tensor)

In [5]:
# lstm = nn.LSTM(input_size=4,hidden_size=100)  
# lstm=lstm.to(device)
# fc=nn.Linear(100,3).to(device)
# learning_rate = 0.05
# criterion = nn.NLLLoss().to(device)

In [6]:
File_object = open('Labels_prostate.txt',"r")
label_txt=File_object.readlines()

 
len(label_txt)

2424

In [7]:
 

genename=pd.read_csv('preprocessed_prostrate.csv')
u=genename['gen_name']

mapz=pd.read_csv('sequence.csv')
len(u)

2424

In [9]:
key=mapz['gene'].tolist()
sequence=mapz['sequence'].tolist()

dictionary = dict(zip(key, sequence))


In [10]:
def gene_preprocessing(text):
  g=""
  u=0
  for i in text:
    if  ord(i)<=90 and ord(i)>=65:
      g=g+i.lower()
    else:
      g=g+i
  return(g)
len(genename['gen_name'])
 

2424

In [11]:
loss_epoch=0
a=0
b=0
c=0
d=0
mint=99999999999999
maxt=-1
total_gene=[]
total_label=[]
for V in tqdm.tqdm(range(len(genename['gen_name']))):
    j=genename['gen_name'][V]
    GN=gene_preprocessing(j)
    #print(GN)
    lab=int(label_txt[V].replace('\n',''))
    #print(lab)
    if GN not in dictionary.keys():

        continue
#     print(GN)
    lin2TenGene=np.array(lineToTensor(dictionary[GN][:70]))
    if(lab==0):
#         if a>1000:
#             continue
        a=a+1
    elif lab==1:
#         if b>1000:
#             continue
        b=b+1
#     elif(lab==2):
# #         if c>1000:
# #             continue
#         c=c+1
#         total_gene.append(lin2TenGene)
#         total_label.append(lab)
#         total_gene.append(lin2TenGene)
#         total_label.append(lab)

    total_gene.append(lin2TenGene)
    cc=lineToTensor(dictionary[GN][:70])
#     print(cc)
#     print(cc[:,0,:].shape)
    total_label.append(lab)
    
    
print(a,b,c,d)



100%|██████████| 2424/2424 [00:03<00:00, 813.85it/s]

787 976 0 0


In [12]:
for V in tqdm.tqdm(range(len(genename['gen_name']))):
    j=genename['gen_name'][V]
    GN=gene_preprocessing(j)
    #print(GN)
    lab=int(label_txt[V].replace('\n',''))
    #print(lab)
    if GN not in dictionary.keys():

        continue
    mint=min (len(dictionary[GN][:50]),mint)
    maxt=max (len(dictionary[GN][:50]),maxt)
#     print(GN)
    lin2TenGene=np.array(lineToTensor(dictionary[GN][:70]))
    if(lab==0):
        
        if a>975:
            continue
        else:
            total_gene.append(lin2TenGene)
            total_label.append(lab)
            
            a=a+1
    elif lab==1:
        continue


    
print(a,b,c,d)
print(mint,maxt)

100%|██████████| 2424/2424 [00:01<00:00, 1683.15it/s]

976 976 0 0
50 50


In [13]:
print(len(total_gene))
print(len(total_label))

1952
1952


In [14]:
df = pd.DataFrame({'gen_name':total_gene,'gen_label':total_label})
df.to_csv('Prostrate_LSTM_traintest.csv')
print(len(df))        
df['gen_name'][0].shape

1952


(70, 1, 4)

In [15]:
class SequenceFolder(data.Dataset):
    def __init__(self,root):
        self.dataset=root
        
    
    def __len__(self):
#         print(len(self.dataset))
        return len(self.dataset)       

    def __getitem__(self, index):
         return (np.array(total_gene[index]) ,np.array(total_label[index]))
#         print(self.dataset['gen_name'][index])          
#         try:
           
#         except :
            
total_set=SequenceFolder(df)  
print(len(total_set))
u=0
for x in total_set:
    print(u)
#     print(x)
    u=u+1
    print("yes")
    

1952
0
yes
1
yes
2
yes
3
yes
4
yes
5
yes
6
yes
7
yes
8
yes
9
yes
10
yes
11
yes
12
yes
13
yes
14
yes
15
yes
16
yes
17
yes
18
yes
19
yes
20
yes
21
yes
22
yes
23
yes
24
yes
25
yes
26
yes
27
yes
28
yes
29
yes
30
yes
31
yes
32
yes
33
yes
34
yes
35
yes
36
yes
37
yes
38
yes
39
yes
40
yes
41
yes
42
yes
43
yes
44
yes
45
yes
46
yes
47
yes
48
yes
49
yes
50
yes
51
yes
52
yes
53
yes
54
yes
55
yes
56
yes
57
yes
58
yes
59
yes
60
yes
61
yes
62
yes
63
yes
64
yes
65
yes
66
yes
67
yes
68
yes
69
yes
70
yes
71
yes
72
yes
73
yes
74
yes
75
yes
76
yes
77
yes
78
yes
79
yes
80
yes
81
yes
82
yes
83
yes
84
yes
85
yes
86
yes
87
yes
88
yes
89
yes
90
yes
91
yes
92
yes
93
yes
94
yes
95
yes
96
yes
97
yes
98
yes
99
yes
100
yes
101
yes
102
yes
103
yes
104
yes
105
yes
106
yes
107
yes
108
yes
109
yes
110
yes
111
yes
112
yes
113
yes
114
yes
115
yes
116
yes
117
yes
118
yes
119
yes
120
yes
121
yes
122
yes
123
yes
124
yes
125
yes
126
yes
127
yes
128
yes
129
yes
130
yes
131
yes
132
yes
133
yes
134
yes
135
yes
136
yes
137
yes
1

In [16]:
batch_size = 4
validation_split = .2
shuffle_dataset = True
random_seed= 42

# Creating data indices for training and validation splits:
dataset_size = len(total_set)
indices = list(range(dataset_size))
split = int(np.floor(validation_split * dataset_size))
if shuffle_dataset :
    np.random.seed(random_seed)
    np.random.shuffle(indices)
train_indices, val_indices = indices[split:], indices[:split]

# Creating PT data samplers and loaders:
train_sampler = SubsetRandomSampler(train_indices)
valid_sampler = SubsetRandomSampler(val_indices)

train_loader = torch.utils.data.DataLoader(total_set, batch_size=batch_size, 
                                           sampler=train_sampler,drop_last=True)
validation_loader = torch.utils.data.DataLoader(total_set, batch_size=batch_size,
                                                sampler=valid_sampler,drop_last=True)


In [17]:
for x,y in validation_loader:
    print(x.shape)

torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([

In [50]:
lstm = nn.LSTM(input_size=4,hidden_size=200,bidirectional=True) #input_size hidden_size num_layers 
lstm2=nn.LSTM(input_size=400,hidden_size=200)
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        
        self.fc1=nn.Linear(200, 600)
        self.bn1=nn.BatchNorm1d(num_features=600)
        
        self.relu=nn.ReLU(inplace=True)
        self.fc2=nn.Linear(600, 300)
        self.bn2=nn.BatchNorm1d(num_features=300)

        self.fc3=nn.Linear(300, 100)
        self.bn3=nn.BatchNorm1d(num_features=100)
        
        self.fc4=nn.Linear(100, 2)
        self.sigm=nn.Sigmoid()
        self.dropout1=nn.Dropout(0.2)
        self.dropout2=nn.Dropout(0.3)
        

    def forward(self, x):
        y=self.sigm(self.fc4(self.bn3(self.fc3(self.bn2(self.dropout2(self.relu(self.fc2(self.bn1(self.dropout1(self.relu(self.fc1(x))))))))))))
        return(y)
    


!nvidia-smi

Tue Jun 11 22:50:54 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0  On |                  N/A |
| 57%   73C    P2   136W / 250W |   2565MiB / 11172MiB |     30%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 49%   83C    P2   161W / 250W |   5497MiB / 11172MiB |     88%      Default |
+-------------------------------+----------------------+----------------------+
|   2  G

In [54]:
device='cuda:0'
model1=lstm.to(device)
model2=MLP().to(device)
model3=lstm2.to(device)
criterion = nn.CrossEntropyLoss()
optim_params = [
    {'params': model1.parameters(), 'lr':0.0001},
    {'params': model2.parameters(), 'lr':0.0001},
    {'params': model3.parameters(), 'lr':0.0001}
        
]
optimizer = torch.optim.Adam(optim_params)


In [55]:
epoch=10000
#3, 50, 1, 4

In [ ]:
for i in range(epoch):
        total_correct=0
        total=0
        confusion_matrix = torch.zeros(2, 2)
    
        for GN,lab in (validation_loader):
#             gen_nam=GN[0]
           
            seq=GN
            seq=seq[:,:,0,:].permute(1,0,2)
            
            
            
            lab=lab.to(device)
            inp=seq.to(device)
        
            if inp.shape[1]==2:
                continue
            
            
            h0 = torch.zeros(2, 4, 200).to(device)   #(num_layers * num_directions, batch, hidden_size)
            c0 = torch.zeros(2, 4, 200).to(device)
            h_x2=c_x2=torch.zeros(1, 4, 200).to(device)
            output, (hn, cn) = model1(inp, (h0, c0))  
            output,(_,_)=model3(output,(h_x2,c_x2))
#             print(output.shape)
            q1,q2,q3=output.shape
            out_last=((output[q1-1]))
            
            After_fc=model2(out_last)

            _, preds = torch.max(After_fc, 1)
            total_correct=total_correct+torch.sum(preds.long()==lab.long().to(device))
            total=total+4
            
            for t, p in zip(lab.view(-1), preds.view(-1)):
 
                confusion_matrix[t.long(), p.long()] += 1
        print(total_correct,total)
        print(confusion_matrix)
    
    
    
    
    
    
    
        loss_epoch=0
        loss_batch=0
        u=0
        for GN,lab in (train_loader):
            
#             gen_nam=GN[0]
            seq=GN
            seq=seq[:,:,0,:].permute(1,0,2)
            lab=lab.to(device)
            inp=seq.to(device)
#             print(inp.shape)

             
            h0 = torch.zeros(2, 4, 200).to(device)   #(num_layers * num_directions, batch, hidden_size)
            c0 = torch.zeros(2, 4, 200).to(device)
            if inp.shape[1]==2:
                continue
            output, (hn, cn) = model1(inp, (h0, c0)) 
            h_x2=c_x2=torch.zeros(1, 4, 200).to(device)
            output,(_,_)=model3(output,(h_x2,c_x2))
            

            q1,q2,q3=output.shape
            out_last=((output[q1-1]))
            After_fc=model2(out_last)

            loss = criterion(After_fc, lab).to(device)
            loss_batch=loss
            
            

            
            u=u+1
#             if u%4==0:
            loss_epoch=loss_epoch+loss_batch
            loss_batch.backward()
            optimizer.step()
            optimizer.zero_grad()
            
                
        print(loss_epoch)

 
 

tensor(177, device='cuda:0') 388
tensor([[128.,  65.],
        [146.,  49.]])
tensor(270.7516, device='cuda:0', grad_fn=<AddBackward0>)
tensor(177, device='cuda:0') 388
tensor([[126.,  67.],
        [144.,  51.]])
tensor(270.7054, device='cuda:0', grad_fn=<AddBackward0>)
tensor(202, device='cuda:0') 388
tensor([[139.,  54.],
        [132.,  63.]])
tensor(270.8701, device='cuda:0', grad_fn=<AddBackward0>)
tensor(193, device='cuda:0') 388
tensor([[135.,  57.],
        [138.,  58.]])
tensor(270.5135, device='cuda:0', grad_fn=<AddBackward0>)
tensor(205, device='cuda:0') 388
tensor([[138.,  56.],
        [127.,  67.]])
tensor(270.8338, device='cuda:0', grad_fn=<AddBackward0>)
tensor(199, device='cuda:0') 388
tensor([[137.,  56.],
        [133.,  62.]])
tensor(270.8381, device='cuda:0', grad_fn=<AddBackward0>)
tensor(187, device='cuda:0') 388
tensor([[129.,  64.],
        [137.,  58.]])
tensor(270.1692, device='cuda:0', grad_fn=<AddBackward0>)
tensor(186, device='cuda:0') 388
tensor([[122., 

tensor(269.9371, device='cuda:0', grad_fn=<AddBackward0>)
tensor(202, device='cuda:0') 388
tensor([[136.,  57.],
        [129.,  66.]])
tensor(270.3561, device='cuda:0', grad_fn=<AddBackward0>)
tensor(195, device='cuda:0') 388
tensor([[129.,  63.],
        [130.,  66.]])
tensor(270.6809, device='cuda:0', grad_fn=<AddBackward0>)
tensor(182, device='cuda:0') 388
tensor([[125.,  68.],
        [138.,  57.]])
tensor(270.0259, device='cuda:0', grad_fn=<AddBackward0>)
tensor(187, device='cuda:0') 388
tensor([[123.,  70.],
        [131.,  64.]])
tensor(270.3875, device='cuda:0', grad_fn=<AddBackward0>)
tensor(200, device='cuda:0') 388
tensor([[133.,  61.],
        [127.,  67.]])
tensor(270.0122, device='cuda:0', grad_fn=<AddBackward0>)
tensor(194, device='cuda:0') 388
tensor([[132.,  61.],
        [133.,  62.]])
tensor(270.4535, device='cuda:0', grad_fn=<AddBackward0>)
tensor(185, device='cuda:0') 388
tensor([[124.,  68.],
        [135.,  61.]])
tensor(269.9643, device='cuda:0', grad_fn=<AddBa

tensor(202, device='cuda:0') 388
tensor([[127.,  66.],
        [120.,  75.]])
tensor(270.5819, device='cuda:0', grad_fn=<AddBackward0>)
tensor(171, device='cuda:0') 388
tensor([[106.,  87.],
        [130.,  65.]])
tensor(270.3129, device='cuda:0', grad_fn=<AddBackward0>)
tensor(207, device='cuda:0') 388
tensor([[119.,  75.],
        [106.,  88.]])
tensor(270.3893, device='cuda:0', grad_fn=<AddBackward0>)
tensor(180, device='cuda:0') 388
tensor([[105.,  88.],
        [120.,  75.]])
tensor(270.8294, device='cuda:0', grad_fn=<AddBackward0>)
tensor(192, device='cuda:0') 388
tensor([[116.,  77.],
        [119.,  76.]])
tensor(270.4316, device='cuda:0', grad_fn=<AddBackward0>)
tensor(188, device='cuda:0') 388
tensor([[112.,  80.],
        [120.,  76.]])
tensor(270.1722, device='cuda:0', grad_fn=<AddBackward0>)
tensor(183, device='cuda:0') 388
tensor([[113.,  80.],
        [125.,  70.]])
tensor(270.0664, device='cuda:0', grad_fn=<AddBackward0>)
tensor(195, device='cuda:0') 388
tensor([[115., 

tensor(270.3738, device='cuda:0', grad_fn=<AddBackward0>)
tensor(190, device='cuda:0') 388
tensor([[140.,  54.],
        [144.,  50.]])
tensor(270.2429, device='cuda:0', grad_fn=<AddBackward0>)
tensor(195, device='cuda:0') 388
tensor([[145.,  49.],
        [144.,  50.]])
tensor(270.0989, device='cuda:0', grad_fn=<AddBackward0>)
tensor(198, device='cuda:0') 388
tensor([[144.,  48.],
        [142.,  54.]])
tensor(270.5934, device='cuda:0', grad_fn=<AddBackward0>)
tensor(176, device='cuda:0') 388
tensor([[132.,  61.],
        [151.,  44.]])
tensor(270.4791, device='cuda:0', grad_fn=<AddBackward0>)
tensor(183, device='cuda:0') 388
tensor([[140.,  53.],
        [152.,  43.]])
tensor(270.2680, device='cuda:0', grad_fn=<AddBackward0>)
tensor(174, device='cuda:0') 388
tensor([[139.,  54.],
        [160.,  35.]])
tensor(270.2914, device='cuda:0', grad_fn=<AddBackward0>)
tensor(199, device='cuda:0') 388
tensor([[153.,  41.],
        [148.,  46.]])
tensor(270.1954, device='cuda:0', grad_fn=<AddBa

tensor(221, device='cuda:0') 388
tensor([[133.,  60.],
        [107.,  88.]])
tensor(270.4860, device='cuda:0', grad_fn=<AddBackward0>)
tensor(208, device='cuda:0') 388
tensor([[122.,  70.],
        [110.,  86.]])
tensor(270.2176, device='cuda:0', grad_fn=<AddBackward0>)
tensor(190, device='cuda:0') 388
tensor([[113.,  81.],
        [117.,  77.]])
tensor(270.2719, device='cuda:0', grad_fn=<AddBackward0>)
tensor(192, device='cuda:0') 388
tensor([[106.,  86.],
        [110.,  86.]])
tensor(270.3759, device='cuda:0', grad_fn=<AddBackward0>)
tensor(203, device='cuda:0') 388
tensor([[121.,  72.],
        [113.,  82.]])
tensor(270.3497, device='cuda:0', grad_fn=<AddBackward0>)
tensor(207, device='cuda:0') 388
tensor([[127.,  66.],
        [115.,  80.]])
tensor(270.2158, device='cuda:0', grad_fn=<AddBackward0>)
tensor(188, device='cuda:0') 388
tensor([[116.,  77.],
        [123.,  72.]])
tensor(270.3329, device='cuda:0', grad_fn=<AddBackward0>)
tensor(194, device='cuda:0') 388
tensor([[124., 

In [34]:
torch.save(model1.state_dict(), '1AnkitBiLSTMprostrate1.pt')
torch.save(model2.state_dict(), '2AnkitBiLSTMprostrate2.pt')#2283/3908
torch.save(model3.state_dict(), '3AnkitBiLSTMprostrate3.pt')