In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

1.0.1.post2
True


In [2]:
from torch import nn
import numpy as np
from torch import nn
import torch.nn.functional as F

In [3]:
import os
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split

In [4]:
seed=4
df=pd.read_csv("preprocessed_prostrate.csv")
no_of_rows,no_of_cols=df.shape
print (no_of_rows,no_of_cols)
df.head()

2424 106


id_ref gen_name        v1        v2       v3       v4      v5       v6  \
0   Hs6-1-6-1      VHL -0.009053  0.036120 -0.13310  0.08359 -0.3133  0.09471   
1  Hs6-1-16-1     SMOX  0.000000  0.000000  0.00000  0.11160  0.0000  0.00000   
2   Hs6-1-6-2   ZNF148  0.189100 -0.175300  0.20240  0.05745 -0.5522 -0.04709   
3  Hs6-1-10-2   MAP4K2  0.335300  0.145700  0.02996 -0.03641 -0.2931  0.23760   
4  Hs6-1-15-2    MAPK4  0.310600  0.008775  0.51170 -0.05886 -0.5037  0.36220   

        v7      v8  ...     v95      v96       v97      v98           v99  \
0 -0.19860  0.1129  ... -0.1065 -0.19410 -0.109500 -0.16090 -2.267000e-01   
1  0.00000  0.0000  ...  0.0000  0.00000  0.000000  0.17460 -5.180000e-10   
2 -0.19840 -0.2156  ...  0.1284 -0.18470  0.007602  0.02113  4.399000e-01   
3 -0.01799  0.1953  ...  0.3081 -0.25550  0.255800 -0.08655  3.707000e-02   
4  0.24620  0.4525  ...  0.3401 -0.04517  0.493200 -0.22720 -1.430000e-01   

      v100     v101      v102    v103    v104  
0 -0.06939 -0.22780 -0.317900 -0.3523 -0.2771  
1  0.00000  0.00000  0.000000 -0.3898 -0.1275  
2 -0.06516  0.01167  0.304800  0.3409 -0.1266  
3  0.03404  0.13550 -0.008265  0.1549  0.4213  
4  0.26500  0.14160  0.334100  0.3155  0.5046  

[5 rows x 106 columns]

In [5]:
header_of_pd=['v'+str(i+1) for i in range(no_of_cols-2)]
X=np.array(df[header_of_pd])
print(X.shape)

(2424, 104)


In [6]:
fil=open('Labels_prostate.txt','r')
tmp=list()
for line in fil:
	tmp.append(int(line))

Y=np.array(tmp)


In [7]:
augmented_X=[]
augmented_Y=[]
a=0
b=0
c=0
d=0
choice=0
t=0
for i in Y:
    if i==0:
        
        choice=1
        a=a+choice
    elif i==1:
        choice=1
        b=b+choice
    for u in range(choice):
        augmented_X.append(X[t])
        augmented_Y.append(Y[t])
    t=t+1
    
print(a,b)
augmented_X=np.array(augmented_X)
augmented_Y=np.array(augmented_Y)

1170 1254


In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(augmented_X,augmented_Y,test_size=0.20,random_state=2)
print(X_test.shape)

(485, 104)


In [12]:
class Net(torch.nn.Module):
    def __init__(self, n_feature,out_features):
        super(Net, self).__init__()
        self.hidden1 = torch.nn.Linear(n_feature,900)
        self.hidden2 = torch.nn.Linear(900,600)
        self.hidden3 = torch.nn.Linear(600,400)
        self.hidden4 = torch.nn.Linear(400,100)
        self.hidden5 =torch.nn.Linear (100,10)
        self.predict = torch.nn.Linear(10,out_features)
        self.bn1 = nn.BatchNorm1d(num_features=900)
        self.bn2 = nn.BatchNorm1d(num_features=600)
        self.bn3 = nn.BatchNorm1d(num_features=400)
        self.bn4 = nn.BatchNorm1d(num_features=100)
        self.bn5 = nn.BatchNorm1d(num_features=10)
    def forward(self, x):
        x = F.relu(self.hidden1(x))
#         x=self.bn1(x)
        x = F.relu(self.hidden2(x))
#         x=self.bn2(x)
        x =F.relu(self.hidden3(x))
        x=self.bn3(x)
        x =F.relu(self.hidden4(x))
        x=self.bn4(x)
        x =F.relu(self.hidden5(x))
#         x=self.bn5(x)
        
        x=F.relu(self.predict(x))
        return x
def accurate():
    total = X_test.shape[0]
    x_test=torch.tensor(X_test,dtype=torch.float)
    y_test=torch.tensor(Y_test,dtype=torch.long)
    outputs = MP(x_test)
    _, predicted = torch.max(outputs.data, 1)
    correct = (predicted.cpu() == y_test).sum()
    confusion_matrix = torch.zeros(2, 2)
    print('Accuracy of the network on the test data: %d %%' % (100 * correct / total))
    for t, p in zip(y_test.view(-1), predicted.view(-1)):
        confusion_matrix[t.long(), p.long()] += 1
    print(confusion_matrix)

In [13]:
MP=Net(104,2)

inp=torch.tensor(X_test,dtype=torch.float)

criterion = nn.CrossEntropyLoss()
target=torch.tensor(np.zeros((4)),dtype=torch.long)
#output = criterion(mid, target)

optimizer = torch.optim.Adam(MP.parameters(), lr = 0.01)

epoch=100
batch=10

sizez=(np.array(X_train)).shape[0]
print (sizez)




1939


In [14]:

epoch=10000
def trainz():
    no_batch=(sizez//batch)
    for i in range (epoch):
        start=0
        NET_LOSS=0
        for j in range(no_batch+1):

            stop=start+batch
            if(stop<=sizez):
                  stop=stop
            else:
                  stop=sizez
        if start>=sizez:
              break

        x_batch=torch.tensor(X_train[start:stop],dtype=torch.float)
        y_batch=torch.tensor(Y_train[start:stop],dtype=torch.long)

        out_batch=MP(x_batch)
        LOSS_BATCH=criterion(out_batch,y_batch)
        optimizer.zero_grad()
        LOSS_BATCH.backward()
        optimizer.step()
        NET_LOSS=NET_LOSS+LOSS_BATCH
#       print(str(LOSS_BATCH)+"___"+str(j))
        start=start+batch
        if start>=sizez or start>stop:
              break
        accurate()
        print(NET_LOSS)

trainz()


Accuracy of the network on the test data: 64 %
tensor([[237.,  14.],
        [160.,  74.]])
tensor(0.6430, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 72 %
tensor([[200.,  51.],
        [ 80., 154.]])
tensor(0.5904, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 79 %
tensor([[205.,  46.],
        [ 55., 179.]])
tensor(0.4339, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[204.,  47.],
        [ 41., 193.]])
tensor(0.3199, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 82 %
tensor([[204.,  47.],
        [ 40., 194.]])
tensor(0.2407, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[204.,  47.],
        [ 41., 193.]])
tensor(0.1778, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[204.,  47.],
        [ 42., 192.]])
tensor(0.1294, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 81 %
tensor([[203.,  48.],
        [ 42.,

tensor([[201.,  50.],
        [ 43., 191.]])
tensor(3.1471e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(3.0518e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(3.0518e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(3.0518e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.9564e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.9564e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.8610e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.8

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.6703e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.6703e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.6703e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.6703e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.5749e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.5749e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.5749e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.4796e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.3842e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.2888e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.2888e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.2888e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(2.0981e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([

tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9

tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.8120e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.8120e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9073e-06, grad_fn=<AddBackward0>)
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])
tensor(1.9

KeyboardInterrupt: 

In [15]:
torch.save(MP.state_dict(), "80MLP_prostate.pt")



In [ ]:
Accuracy of the network on the test data: 80 %
tensor([[201.,  50.],
        [ 43., 191.]])