In [2]:
from os import path

import torch
print(torch.__version__)
print(torch.cuda.is_available())
from torchvision import datasets, transforms
import pandas as pd
import numpy as np
from path import Path
import torch.utils.data as data

from torch import nn
import numpy as np
import pandas as pd
import tqdm

import os
import os
from sklearn.model_selection import train_test_split
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn.functional as F


all_letters="ACTG"

1.0.1.post2
True


In [3]:
device='cuda:2'
x=torch.zeros(5,5).to(device)

In [4]:
def letterToIndex(letter):
    return all_letters.find(letter)
def letterToTensor(letter):
  tensor=torch.zeros(1,4)
  tensor[0][letterToIndex(letter)] = 1
  return tensor
def lineToTensor(line):
  tensor=torch.zeros(len(line),1,4)
  for li,letters in enumerate(line):
    tensor[li][0][letterToIndex(letters)]=1
  return(tensor)

In [5]:
File_object = open('label0.txt',"r")
label_txt=File_object.readlines()

 
len(label_txt)

4655

In [6]:
genename=pd.read_csv('preprocessed_BCLL.csv')
u=genename['B']
#print(genename)
# print(u)
mapz=pd.read_csv('sequence.csv')
len(u)

4655

In [7]:
key=mapz['gene'].tolist()
sequence=mapz['sequence'].tolist()
#print(key)
#print(sequence)
dictionary = dict(zip(key, sequence))

In [8]:
def gene_preprocessing(text):
  g=""
  u=0
  for i in text:
    if  ord(i)<=90 and ord(i)>=65:
      g=g+i.lower()
    else:
      g=g+i
  return(g)
len(genename['B'])
 

4655

In [9]:
loss_epoch=0
a=0
b=0
c=0
d=0
mint=99999999999999
maxt=-1
total_gene=[]
total_label=[]
count=0
for V in tqdm.tqdm(range(len(genename['B']))):
    j=genename['B'][V]
    GN=gene_preprocessing(j)
    #print(GN)
    lab=int(label_txt[V].replace('\n',''))
    #print(lab)
    if GN not in dictionary.keys():

        continue
#     print(GN)
    lin2TenGene=np.array(lineToTensor(dictionary[GN][:70]))
    if(lab==0):
        
#         if a>1000:
#       continue
        count=65
        a=a+count
        
    elif lab==1:
#         if b>1000:
#             continue
        count=8
        b=b+count
        
    else :
        count=1
        c=c+count
        
    for u in range(count):
        total_gene.append(lin2TenGene)
        cc=lineToTensor(dictionary[GN][:70])
    #     print(cc)
    #     print(cc[:,0,:].shape)
        total_label.append(lab)


print(a,b,c,d)



100%|██████████| 4655/4655 [00:14<00:00, 320.24it/s]

3640 3504 3781 0


In [10]:
print(len(total_gene))
print(len(total_label))

10925
10925


In [12]:
df = pd.DataFrame({'gen_name':total_gene,'gen_label':total_label})
df.to_csv('BCLL_LSTM_traintest.csv')
print(len(df))        
df['gen_name'][0].shape

10925


(70, 1, 4)

In [13]:
class SequenceFolder(data.Dataset):
    def __init__(self,root):
        self.dataset=root
        
    
    def __len__(self):
#         print(len(self.dataset))
        return len(self.dataset)       

    def __getitem__(self, index):
         return (np.array(total_gene[index]) ,np.array(total_label[index]))
#         print(self.dataset['gen_name'][index])          
#         try:
           
#         except :
            
total_set=SequenceFolder(df)  
print(len(total_set))
u=0
for x in total_set:
    print(u)
#     print(x)
    u=u+1
    print("yes")
    

10925
0
yes
1
yes
2
yes
3
yes
4
yes
5
yes
6
yes
7
yes
8
yes
9
yes
10
yes
11
yes
12
yes
13
yes
14
yes
15
yes
16
yes
17
yes
18
yes
19
yes
20
yes
21
yes
22
yes
23
yes
24
yes
25
yes
26
yes
27
yes
28
yes
29
yes
30
yes
31
yes
32
yes
33
yes
34
yes
35
yes
36
yes
37
yes
38
yes
39
yes
40
yes
41
yes
42
yes
43
yes
44
yes
45
yes
46
yes
47
yes
48
yes
49
yes
50
yes
51
yes
52
yes
53
yes
54
yes
55
yes
56
yes
57
yes
58
yes
59
yes
60
yes
61
yes
62
yes
63
yes
64
yes
65
yes
66
yes
67
yes
68
yes
69
yes
70
yes
71
yes
72
yes
73
yes
74
yes
75
yes
76
yes
77
yes
78
yes
79
yes
80
yes
81
yes
82
yes
83
yes
84
yes
85
yes
86
yes
87
yes
88
yes
89
yes
90
yes
91
yes
92
yes
93
yes
94
yes
95
yes
96
yes
97
yes
98
yes
99
yes
100
yes
101
yes
102
yes
103
yes
104
yes
105
yes
106
yes
107
yes
108
yes
109
yes
110
yes
111
yes
112
yes
113
yes
114
yes
115
yes
116
yes
117
yes
118
yes
119
yes
120
yes
121
yes
122
yes
123
yes
124
yes
125
yes
126
yes
127
yes
128
yes
129
yes
130
yes
131
yes
132
yes
133
yes
134
yes
135
yes
136
yes
137
yes


1834
yes
1835
yes
1836
yes
1837
yes
1838
yes
1839
yes
1840
yes
1841
yes
1842
yes
1843
yes
1844
yes
1845
yes
1846
yes
1847
yes
1848
yes
1849
yes
1850
yes
1851
yes
1852
yes
1853
yes
1854
yes
1855
yes
1856
yes
1857
yes
1858
yes
1859
yes
1860
yes
1861
yes
1862
yes
1863
yes
1864
yes
1865
yes
1866
yes
1867
yes
1868
yes
1869
yes
1870
yes
1871
yes
1872
yes
1873
yes
1874
yes
1875
yes
1876
yes
1877
yes
1878
yes
1879
yes
1880
yes
1881
yes
1882
yes
1883
yes
1884
yes
1885
yes
1886
yes
1887
yes
1888
yes
1889
yes
1890
yes
1891
yes
1892
yes
1893
yes
1894
yes
1895
yes
1896
yes
1897
yes
1898
yes
1899
yes
1900
yes
1901
yes
1902
yes
1903
yes
1904
yes
1905
yes
1906
yes
1907
yes
1908
yes
1909
yes
1910
yes
1911
yes
1912
yes
1913
yes
1914
yes
1915
yes
1916
yes
1917
yes
1918
yes
1919
yes
1920
yes
1921
yes
1922
yes
1923
yes
1924
yes
1925
yes
1926
yes
1927
yes
1928
yes
1929
yes
1930
yes
1931
yes
1932
yes
1933
yes
1934
yes
1935
yes
1936
yes
1937
yes
1938
yes
1939
yes
1940
yes
1941
yes
1942
yes
1943
yes
1944
yes
1

3079
yes
3080
yes
3081
yes
3082
yes
3083
yes
3084
yes
3085
yes
3086
yes
3087
yes
3088
yes
3089
yes
3090
yes
3091
yes
3092
yes
3093
yes
3094
yes
3095
yes
3096
yes
3097
yes
3098
yes
3099
yes
3100
yes
3101
yes
3102
yes
3103
yes
3104
yes
3105
yes
3106
yes
3107
yes
3108
yes
3109
yes
3110
yes
3111
yes
3112
yes
3113
yes
3114
yes
3115
yes
3116
yes
3117
yes
3118
yes
3119
yes
3120
yes
3121
yes
3122
yes
3123
yes
3124
yes
3125
yes
3126
yes
3127
yes
3128
yes
3129
yes
3130
yes
3131
yes
3132
yes
3133
yes
3134
yes
3135
yes
3136
yes
3137
yes
3138
yes
3139
yes
3140
yes
3141
yes
3142
yes
3143
yes
3144
yes
3145
yes
3146
yes
3147
yes
3148
yes
3149
yes
3150
yes
3151
yes
3152
yes
3153
yes
3154
yes
3155
yes
3156
yes
3157
yes
3158
yes
3159
yes
3160
yes
3161
yes
3162
yes
3163
yes
3164
yes
3165
yes
3166
yes
3167
yes
3168
yes
3169
yes
3170
yes
3171
yes
3172
yes
3173
yes
3174
yes
3175
yes
3176
yes
3177
yes
3178
yes
3179
yes
3180
yes
3181
yes
3182
yes
3183
yes
3184
yes
3185
yes
3186
yes
3187
yes
3188
yes
3189
yes
3

4079
yes
4080
yes
4081
yes
4082
yes
4083
yes
4084
yes
4085
yes
4086
yes
4087
yes
4088
yes
4089
yes
4090
yes
4091
yes
4092
yes
4093
yes
4094
yes
4095
yes
4096
yes
4097
yes
4098
yes
4099
yes
4100
yes
4101
yes
4102
yes
4103
yes
4104
yes
4105
yes
4106
yes
4107
yes
4108
yes
4109
yes
4110
yes
4111
yes
4112
yes
4113
yes
4114
yes
4115
yes
4116
yes
4117
yes
4118
yes
4119
yes
4120
yes
4121
yes
4122
yes
4123
yes
4124
yes
4125
yes
4126
yes
4127
yes
4128
yes
4129
yes
4130
yes
4131
yes
4132
yes
4133
yes
4134
yes
4135
yes
4136
yes
4137
yes
4138
yes
4139
yes
4140
yes
4141
yes
4142
yes
4143
yes
4144
yes
4145
yes
4146
yes
4147
yes
4148
yes
4149
yes
4150
yes
4151
yes
4152
yes
4153
yes
4154
yes
4155
yes
4156
yes
4157
yes
4158
yes
4159
yes
4160
yes
4161
yes
4162
yes
4163
yes
4164
yes
4165
yes
4166
yes
4167
yes
4168
yes
4169
yes
4170
yes
4171
yes
4172
yes
4173
yes
4174
yes
4175
yes
4176
yes
4177
yes
4178
yes
4179
yes
4180
yes
4181
yes
4182
yes
4183
yes
4184
yes
4185
yes
4186
yes
4187
yes
4188
yes
4189
yes
4

yes
5242
yes
5243
yes
5244
yes
5245
yes
5246
yes
5247
yes
5248
yes
5249
yes
5250
yes
5251
yes
5252
yes
5253
yes
5254
yes
5255
yes
5256
yes
5257
yes
5258
yes
5259
yes
5260
yes
5261
yes
5262
yes
5263
yes
5264
yes
5265
yes
5266
yes
5267
yes
5268
yes
5269
yes
5270
yes
5271
yes
5272
yes
5273
yes
5274
yes
5275
yes
5276
yes
5277
yes
5278
yes
5279
yes
5280
yes
5281
yes
5282
yes
5283
yes
5284
yes
5285
yes
5286
yes
5287
yes
5288
yes
5289
yes
5290
yes
5291
yes
5292
yes
5293
yes
5294
yes
5295
yes
5296
yes
5297
yes
5298
yes
5299
yes
5300
yes
5301
yes
5302
yes
5303
yes
5304
yes
5305
yes
5306
yes
5307
yes
5308
yes
5309
yes
5310
yes
5311
yes
5312
yes
5313
yes
5314
yes
5315
yes
5316
yes
5317
yes
5318
yes
5319
yes
5320
yes
5321
yes
5322
yes
5323
yes
5324
yes
5325
yes
5326
yes
5327
yes
5328
yes
5329
yes
5330
yes
5331
yes
5332
yes
5333
yes
5334
yes
5335
yes
5336
yes
5337
yes
5338
yes
5339
yes
5340
yes
5341
yes
5342
yes
5343
yes
5344
yes
5345
yes
5346
yes
5347
yes
5348
yes
5349
yes
5350
yes
5351
yes
5352
y

yes
6579
yes
6580
yes
6581
yes
6582
yes
6583
yes
6584
yes
6585
yes
6586
yes
6587
yes
6588
yes
6589
yes
6590
yes
6591
yes
6592
yes
6593
yes
6594
yes
6595
yes
6596
yes
6597
yes
6598
yes
6599
yes
6600
yes
6601
yes
6602
yes
6603
yes
6604
yes
6605
yes
6606
yes
6607
yes
6608
yes
6609
yes
6610
yes
6611
yes
6612
yes
6613
yes
6614
yes
6615
yes
6616
yes
6617
yes
6618
yes
6619
yes
6620
yes
6621
yes
6622
yes
6623
yes
6624
yes
6625
yes
6626
yes
6627
yes
6628
yes
6629
yes
6630
yes
6631
yes
6632
yes
6633
yes
6634
yes
6635
yes
6636
yes
6637
yes
6638
yes
6639
yes
6640
yes
6641
yes
6642
yes
6643
yes
6644
yes
6645
yes
6646
yes
6647
yes
6648
yes
6649
yes
6650
yes
6651
yes
6652
yes
6653
yes
6654
yes
6655
yes
6656
yes
6657
yes
6658
yes
6659
yes
6660
yes
6661
yes
6662
yes
6663
yes
6664
yes
6665
yes
6666
yes
6667
yes
6668
yes
6669
yes
6670
yes
6671
yes
6672
yes
6673
yes
6674
yes
6675
yes
6676
yes
6677
yes
6678
yes
6679
yes
6680
yes
6681
yes
6682
yes
6683
yes
6684
yes
6685
yes
6686
yes
6687
yes
6688
yes
6689
y

7828
yes
7829
yes
7830
yes
7831
yes
7832
yes
7833
yes
7834
yes
7835
yes
7836
yes
7837
yes
7838
yes
7839
yes
7840
yes
7841
yes
7842
yes
7843
yes
7844
yes
7845
yes
7846
yes
7847
yes
7848
yes
7849
yes
7850
yes
7851
yes
7852
yes
7853
yes
7854
yes
7855
yes
7856
yes
7857
yes
7858
yes
7859
yes
7860
yes
7861
yes
7862
yes
7863
yes
7864
yes
7865
yes
7866
yes
7867
yes
7868
yes
7869
yes
7870
yes
7871
yes
7872
yes
7873
yes
7874
yes
7875
yes
7876
yes
7877
yes
7878
yes
7879
yes
7880
yes
7881
yes
7882
yes
7883
yes
7884
yes
7885
yes
7886
yes
7887
yes
7888
yes
7889
yes
7890
yes
7891
yes
7892
yes
7893
yes
7894
yes
7895
yes
7896
yes
7897
yes
7898
yes
7899
yes
7900
yes
7901
yes
7902
yes
7903
yes
7904
yes
7905
yes
7906
yes
7907
yes
7908
yes
7909
yes
7910
yes
7911
yes
7912
yes
7913
yes
7914
yes
7915
yes
7916
yes
7917
yes
7918
yes
7919
yes
7920
yes
7921
yes
7922
yes
7923
yes
7924
yes
7925
yes
7926
yes
7927
yes
7928
yes
7929
yes
7930
yes
7931
yes
7932
yes
7933
yes
7934
yes
7935
yes
7936
yes
7937
yes
7938
yes
7

9078
yes
9079
yes
9080
yes
9081
yes
9082
yes
9083
yes
9084
yes
9085
yes
9086
yes
9087
yes
9088
yes
9089
yes
9090
yes
9091
yes
9092
yes
9093
yes
9094
yes
9095
yes
9096
yes
9097
yes
9098
yes
9099
yes
9100
yes
9101
yes
9102
yes
9103
yes
9104
yes
9105
yes
9106
yes
9107
yes
9108
yes
9109
yes
9110
yes
9111
yes
9112
yes
9113
yes
9114
yes
9115
yes
9116
yes
9117
yes
9118
yes
9119
yes
9120
yes
9121
yes
9122
yes
9123
yes
9124
yes
9125
yes
9126
yes
9127
yes
9128
yes
9129
yes
9130
yes
9131
yes
9132
yes
9133
yes
9134
yes
9135
yes
9136
yes
9137
yes
9138
yes
9139
yes
9140
yes
9141
yes
9142
yes
9143
yes
9144
yes
9145
yes
9146
yes
9147
yes
9148
yes
9149
yes
9150
yes
9151
yes
9152
yes
9153
yes
9154
yes
9155
yes
9156
yes
9157
yes
9158
yes
9159
yes
9160
yes
9161
yes
9162
yes
9163
yes
9164
yes
9165
yes
9166
yes
9167
yes
9168
yes
9169
yes
9170
yes
9171
yes
9172
yes
9173
yes
9174
yes
9175
yes
9176
yes
9177
yes
9178
yes
9179
yes
9180
yes
9181
yes
9182
yes
9183
yes
9184
yes
9185
yes
9186
yes
9187
yes
9188
yes
9

yes
10328
yes
10329
yes
10330
yes
10331
yes
10332
yes
10333
yes
10334
yes
10335
yes
10336
yes
10337
yes
10338
yes
10339
yes
10340
yes
10341
yes
10342
yes
10343
yes
10344
yes
10345
yes
10346
yes
10347
yes
10348
yes
10349
yes
10350
yes
10351
yes
10352
yes
10353
yes
10354
yes
10355
yes
10356
yes
10357
yes
10358
yes
10359
yes
10360
yes
10361
yes
10362
yes
10363
yes
10364
yes
10365
yes
10366
yes
10367
yes
10368
yes
10369
yes
10370
yes
10371
yes
10372
yes
10373
yes
10374
yes
10375
yes
10376
yes
10377
yes
10378
yes
10379
yes
10380
yes
10381
yes
10382
yes
10383
yes
10384
yes
10385
yes
10386
yes
10387
yes
10388
yes
10389
yes
10390
yes
10391
yes
10392
yes
10393
yes
10394
yes
10395
yes
10396
yes
10397
yes
10398
yes
10399
yes
10400
yes
10401
yes
10402
yes
10403
yes
10404
yes
10405
yes
10406
yes
10407
yes
10408
yes
10409
yes
10410
yes
10411
yes
10412
yes
10413
yes
10414
yes
10415
yes
10416
yes
10417
yes
10418
yes
10419
yes
10420
yes
10421
yes
10422
yes
10423
yes
10424
yes
10425
yes
10426
yes
10427


In [14]:
batch_size = 4
validation_split = .2
shuffle_dataset = True
random_seed= 42

# Creating data indices for training and validation splits:
dataset_size = len(total_set)
indices = list(range(dataset_size))
split = int(np.floor(validation_split * dataset_size))
if shuffle_dataset :
    np.random.seed(random_seed)
    np.random.shuffle(indices)
train_indices, val_indices = indices[split:], indices[:split]

# Creating PT data samplers and loaders:
train_sampler = SubsetRandomSampler(train_indices)
valid_sampler = SubsetRandomSampler(val_indices)

train_loader = torch.utils.data.DataLoader(total_set, batch_size=batch_size, 
                                           sampler=train_sampler,drop_last=True)
validation_loader = torch.utils.data.DataLoader(total_set, batch_size=batch_size,
                                                sampler=valid_sampler,drop_last=True)


In [15]:
for x,y in validation_loader:
    print(x.shape)

torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([

torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])
torch.Size([4, 70, 1, 4])


In [16]:
lstm = nn.LSTM(input_size=4,hidden_size=300,bidirectional=True) #input_size hidden_size num_layers 
lstm2=nn.LSTM(input_size=600,hidden_size=300)
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        
        self.fc1=nn.Linear(300, 500)
        self.bn1=nn.BatchNorm1d(num_features=500)
        
        self.relu=nn.ReLU(inplace=True)
        self.fc2=nn.Linear(500, 200)
        self.bn2=nn.BatchNorm1d(num_features=200)

        self.fc3=nn.Linear(200, 100)
        self.bn3=nn.BatchNorm1d(num_features=100)
        
        self.fc4=nn.Linear(100, 3)
        self.sigm=nn.Sigmoid()
        self.dropout=nn.Dropout(0.2)
        

    def forward(self, x):
        y=self.sigm(self.fc4(self.bn3(self.fc3(self.bn2(self.dropout(self.relu(self.fc2(self.bn1(self.relu(self.fc1(x)))))))))))
        return(y)
    
device='cuda:7'

x=torch.zeros(5,5).to(device)


In [17]:
device='cuda:4'
model1=lstm.to(device)
model2=MLP().to(device)
model3=lstm2.to(device)
criterion = nn.CrossEntropyLoss()
optim_params = [
    {'params': model1.parameters(), 'lr': 0.0001},
    {'params': model2.parameters(), 'lr':0.0001},
    {'params': model3.parameters(), 'lr':0.0001}
        
]
optimizer = torch.optim.Adam(optim_params)


In [20]:
epoch=10000
#3, 50, 1, 4
for i in range(epoch):
        total_correct=0
        total=0
        confusion_matrix = torch.zeros(3, 3)
    
        for GN,lab in (validation_loader):
#             gen_nam=GN[0]
           
            seq=GN
            seq=seq[:,:,0,:].permute(1,0,2)
            
            
            #print(lab) 
            lab=lab.to(device)
            inp=seq.to(device)
        
            if inp.shape[1]==2:
                continue
            
            
            h0 = torch.zeros(2, 4, 300).to(device)   #(num_layers * num_directions, batch, hidden_size)
            c0 = torch.zeros(2, 4, 300).to(device)
            h_x2=c_x2=torch.zeros(1, 4, 300).to(device)
            output, (hn, cn) = model1(inp, (h0, c0))  
            output,(_,_)=model3(output,(h_x2,c_x2))
#             print(output.shape)
            q1,q2,q3=output.shape
            out_last=((output[q1-1]))
            
            After_fc=model2(out_last)

            _, preds = torch.max(After_fc, 1)
            total_correct=total_correct+torch.sum(preds.long()==lab.long().to(device))
            total=total+4
            
            for t, p in zip(lab.view(-1), preds.view(-1)):
 
                confusion_matrix[t.long(), p.long()] += 1
        print(total_correct,total)
        print(confusion_matrix)
    
    
    
    
    
    
    
        loss_epoch=0
        loss_batch=0
        u=0
        for GN,lab in (train_loader):
            
#             gen_nam=GN[0]
            seq=GN
            seq=seq[:,:,0,:].permute(1,0,2)
            #print(lab)
            lab=lab.to(device)
            inp=seq.to(device)
#             print(inp.shape)

             
            h0 = torch.zeros(2, 4, 300).to(device)   #(num_layers * num_directions, batch, hidden_size)
            c0 = torch.zeros(2, 4, 300).to(device)
            if inp.shape[1]==2:
                continue
            output, (hn, cn) = model1(inp, (h0, c0)) 
            h_x2=c_x2=torch.zeros(1, 4, 300).to(device)
            output,(_,_)=model3(output,(h_x2,c_x2))
            

            q1,q2,q3=output.shape
            out_last=((output[q1-1]))
            After_fc=model2(out_last)

            loss = criterion(After_fc, lab).to(device)
            loss_batch=loss
            
            

            
            u=u+1
#             if u%4==0:
            loss_epoch=loss_epoch+loss_batch
            loss_batch.backward()
            optimizer.step()
            optimizer.zero_grad()
            
                
        print(loss_epoch)

 
 

tensor(1419, device='cuda:4') 2184
tensor([[707.,   1.,  29.],
        [  6.,  99., 620.],
        [ 25.,  84., 613.]])
tensor(1700.7583, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1413, device='cuda:4') 2184
tensor([[708.,   1.,  27.],
        [ 13.,  93., 620.],
        [ 39.,  71., 612.]])
tensor(1714.3282, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1415, device='cuda:4') 2184
tensor([[692.,   0.,  44.],
        [ 11., 130., 585.],
        [ 31.,  98., 593.]])
tensor(1710.4637, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1419, device='cuda:4') 2184
tensor([[707.,   0.,  30.],
        [  7., 127., 591.],
        [ 30., 107., 585.]])
tensor(1680.7428, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1420, device='cuda:4') 2184
tensor([[723.,   1.,  13.],
        [ 11.,  94., 621.],
        [ 52.,  66., 603.]])
tensor(1681.4724, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1421, device='cuda:4') 2184
tensor([[712.,   1.,  24.],
        [  9.,  83., 633.],
        [ 30.,

tensor(1475, device='cuda:4') 2184
tensor([[721.,   1.,  15.],
        [  4.,  70., 652.],
        [  8.,  29., 684.]])
tensor(1639.3004, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1451, device='cuda:4') 2184
tensor([[703.,   1.,  33.],
        [  4.,  77., 645.],
        [ 11.,  39., 671.]])
tensor(1680.4797, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1437, device='cuda:4') 2184
tensor([[717.,   0.,  20.],
        [  5.,  64., 657.],
        [ 24.,  41., 656.]])
tensor(1676.6885, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1428, device='cuda:4') 2184
tensor([[704.,   0.,  33.],
        [  7.,  70., 648.],
        [ 18.,  50., 654.]])
tensor(1642.9983, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1459, device='cuda:4') 2184
tensor([[720.,   0.,  16.],
        [  6.,  68., 652.],
        [ 17.,  34., 671.]])
tensor(1673.0195, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1420, device='cuda:4') 2184
tensor([[677.,   0.,  60.],
        [  8.,  97., 620.],
        [ 14.,

tensor(1473, device='cuda:4') 2184
tensor([[726.,   0.,  11.],
        [  4.,  85., 636.],
        [ 23.,  37., 662.]])
tensor(1645.4114, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1468, device='cuda:4') 2184
tensor([[726.,   4.,   7.],
        [  5.,  91., 630.],
        [ 18.,  52., 651.]])
tensor(1622.3853, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1495, device='cuda:4') 2184
tensor([[718.,   0.,  19.],
        [  4., 127., 595.],
        [ 14.,  57., 650.]])
tensor(1711.2126, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1422, device='cuda:4') 2184
tensor([[684.,   7.,  45.],
        [  4., 116., 606.],
        [ 32.,  68., 622.]])
tensor(1690.9692, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1399, device='cuda:4') 2184
tensor([[650.,   3.,  84.],
        [ 10., 115., 600.],
        [ 31.,  57., 634.]])
tensor(1649.9591, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1457, device='cuda:4') 2184
tensor([[709.,   0.,  27.],
        [  6., 127., 593.],
        [ 32.,

tensor(1517, device='cuda:4') 2184
tensor([[709.,   3.,  24.],
        [  5., 226., 495.],
        [ 21., 119., 582.]])
tensor(1638.5879, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1519, device='cuda:4') 2184
tensor([[695.,   6.,  36.],
        [  8., 227., 490.],
        [ 16., 109., 597.]])
tensor(1649.7465, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1510, device='cuda:4') 2184
tensor([[709.,   1.,  26.],
        [  4., 188., 534.],
        [ 23.,  86., 613.]])
tensor(1633.9713, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1522, device='cuda:4') 2184
tensor([[731.,   0.,   6.],
        [  5., 188., 533.],
        [ 20.,  98., 603.]])
tensor(1647.1010, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1512, device='cuda:4') 2184
tensor([[700.,   2.,  34.],
        [  4., 196., 526.],
        [ 14.,  92., 616.]])
tensor(1628.2327, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1492, device='cuda:4') 2184
tensor([[714.,   3.,  20.],
        [  5., 170., 551.],
        [ 37.,

tensor(1444, device='cuda:4') 2184
tensor([[667.,  31.,  38.],
        [ 18., 206., 502.],
        [ 36., 115., 571.]])
tensor(1720.9420, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1486, device='cuda:4') 2184
tensor([[687.,  26.,  24.],
        [ 17., 227., 482.],
        [ 37., 112., 572.]])
tensor(1732.9352, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1443, device='cuda:4') 2184
tensor([[666.,  20.,  51.],
        [ 12., 198., 516.],
        [ 31., 111., 579.]])
tensor(1728.9032, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1489, device='cuda:4') 2184
tensor([[661.,  20.,  55.],
        [  6., 240., 480.],
        [ 23., 111., 588.]])
tensor(1730.3214, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1428, device='cuda:4') 2184
tensor([[647.,  23.,  66.],
        [  6., 194., 526.],
        [ 38.,  97., 587.]])
tensor(1734.2701, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1374, device='cuda:4') 2184
tensor([[632.,  25.,  80.],
        [ 16., 189., 521.],
        [ 39.,

tensor(1623, device='cuda:4') 2184
tensor([[713.,   1.,  23.],
        [  5., 378., 342.],
        [ 22., 168., 532.]])
tensor(1618.1326, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1553, device='cuda:4') 2184
tensor([[668.,   3.,  65.],
        [  6., 357., 363.],
        [ 20., 174., 528.]])
tensor(1653.7595, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1587, device='cuda:4') 2184
tensor([[685.,   1.,  51.],
        [  7., 350., 369.],
        [ 20., 149., 552.]])
tensor(1592.2786, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1631, device='cuda:4') 2184
tensor([[712.,   1.,  24.],
        [  6., 395., 325.],
        [ 11., 186., 524.]])
tensor(1575.5774, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1641, device='cuda:4') 2184
tensor([[715.,   3.,  18.],
        [  4., 371., 351.],
        [ 13., 154., 555.]])
tensor(1597.8516, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1646, device='cuda:4') 2184
tensor([[703.,   5.,  29.],
        [  5., 394., 326.],
        [ 12.,

tensor(1716, device='cuda:4') 2184
tensor([[720.,   6.,  10.],
        [  6., 466., 254.],
        [ 12., 180., 530.]])
tensor(1547.3661, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1675, device='cuda:4') 2184
tensor([[728.,   2.,   7.],
        [  7., 428., 290.],
        [ 26., 177., 519.]])
tensor(1567.1415, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1689, device='cuda:4') 2184
tensor([[712.,   2.,  23.],
        [  6., 451., 268.],
        [ 20., 176., 526.]])
tensor(1562.3633, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1652, device='cuda:4') 2184
tensor([[703.,   9.,  25.],
        [  7., 425., 294.],
        [ 21., 176., 524.]])
tensor(1555.7863, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1714, device='cuda:4') 2184
tensor([[705.,   4.,  28.],
        [  3., 470., 252.],
        [ 14., 169., 539.]])
tensor(1561.0623, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1637, device='cuda:4') 2184
tensor([[655.,   4.,  77.],
        [  5., 459., 262.],
        [  8.,

tensor(1719, device='cuda:4') 2184
tensor([[663.,   3.,  70.],
        [  8., 513., 205.],
        [  9., 170., 543.]])
tensor(1534.9666, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1737, device='cuda:4') 2184
tensor([[708.,  13.,  15.],
        [ 12., 479., 235.],
        [ 22., 150., 550.]])
tensor(1506.5654, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1758, device='cuda:4') 2184
tensor([[720.,   2.,  14.],
        [  8., 499., 219.],
        [ 25., 158., 539.]])
tensor(1514.7479, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1762, device='cuda:4') 2184
tensor([[725.,   3.,   9.],
        [ 10., 484., 231.],
        [ 28., 141., 553.]])
tensor(1501.0862, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1793, device='cuda:4') 2184
tensor([[724.,   2.,  11.],
        [  7., 526., 192.],
        [ 17., 162., 543.]])
tensor(1519.0354, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1717, device='cuda:4') 2184
tensor([[674.,   4.,  58.],
        [  5., 523., 198.],
        [ 13.,

tensor(1839, device='cuda:4') 2184
tensor([[724.,   4.,   8.],
        [  8., 540., 178.],
        [ 10., 137., 575.]])
tensor(1468.0464, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1805, device='cuda:4') 2184
tensor([[724.,   3.,   9.],
        [  8., 542., 176.],
        [ 25., 158., 539.]])
tensor(1486.1371, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1814, device='cuda:4') 2184
tensor([[711.,   6.,  20.],
        [  9., 555., 162.],
        [ 19., 154., 548.]])
tensor(1502.6946, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1821, device='cuda:4') 2184
tensor([[697.,   2.,  37.],
        [  8., 571., 147.],
        [ 16., 153., 553.]])
tensor(1527.3611, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1712, device='cuda:4') 2184
tensor([[700.,   5.,  32.],
        [  5., 467., 253.],
        [ 21., 156., 545.]])
tensor(1513.2090, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1793, device='cuda:4') 2184
tensor([[707.,   8.,  22.],
        [  4., 538., 184.],
        [ 13.,

tensor(1875, device='cuda:4') 2184
tensor([[716.,   5.,  16.],
        [  4., 584., 138.],
        [ 12., 134., 575.]])
tensor(1426.1593, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1851, device='cuda:4') 2184
tensor([[718.,   5.,  14.],
        [  4., 577., 144.],
        [  8., 158., 556.]])
tensor(1429.3698, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1862, device='cuda:4') 2184
tensor([[721.,   1.,  15.],
        [  5., 581., 139.],
        [ 14., 148., 560.]])
tensor(1428.7075, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1855, device='cuda:4') 2184
tensor([[724.,   4.,   8.],
        [  4., 565., 157.],
        [ 16., 140., 566.]])
tensor(1431.4193, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1790, device='cuda:4') 2184
tensor([[703.,   4.,  29.],
        [  4., 522., 200.],
        [  9., 148., 565.]])
tensor(1457.2013, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1842, device='cuda:4') 2184
tensor([[704.,  11.,  22.],
        [  4., 577., 144.],
        [ 13.,

tensor(1867, device='cuda:4') 2184
tensor([[726.,   1.,   9.],
        [  4., 577., 145.],
        [  8., 150., 564.]])
tensor(1435.0939, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1857, device='cuda:4') 2184
tensor([[707.,   3.,  26.],
        [  5., 589., 132.],
        [ 12., 149., 561.]])
tensor(1451.8582, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1803, device='cuda:4') 2184
tensor([[691.,   4.,  42.],
        [  5., 562., 158.],
        [  7., 165., 550.]])
tensor(1457.7875, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1846, device='cuda:4') 2184
tensor([[699.,   2.,  36.],
        [  3., 589., 133.],
        [ 16., 148., 558.]])
tensor(1461.2097, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1810, device='cuda:4') 2184
tensor([[673.,   3.,  61.],
        [  4., 576., 146.],
        [ 19., 141., 561.]])
tensor(1455.7391, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1837, device='cuda:4') 2184
tensor([[705.,   2.,  29.],
        [  4., 560., 162.],
        [ 16.,

tensor(1867, device='cuda:4') 2184
tensor([[719.,  11.,   7.],
        [  7., 631.,  88.],
        [ 16., 188., 517.]])
tensor(1446.0736, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1834, device='cuda:4') 2184
tensor([[701.,  15.,  20.],
        [ 11., 618.,  97.],
        [ 18., 189., 515.]])
tensor(1455.6709, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1863, device='cuda:4') 2184
tensor([[701.,  12.,  24.],
        [ 10., 634.,  82.],
        [ 20., 173., 528.]])
tensor(1446.5822, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1875, device='cuda:4') 2184
tensor([[702.,  26.,   9.],
        [  4., 639.,  82.],
        [ 17., 171., 534.]])
tensor(1432.1014, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1868, device='cuda:4') 2184
tensor([[701.,  31.,   4.],
        [  4., 642.,  80.],
        [ 11., 186., 525.]])
tensor(1412.9818, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1920, device='cuda:4') 2184
tensor([[707.,  15.,  15.],
        [  4., 672.,  50.],
        [  7.,

tensor(1929, device='cuda:4') 2184
tensor([[703.,   2.,  32.],
        [  4., 699.,  22.],
        [ 12., 183., 527.]])
tensor(1394.8833, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1955, device='cuda:4') 2184
tensor([[722.,   0.,  15.],
        [  4., 691.,  31.],
        [ 19., 160., 542.]])
tensor(1383.0057, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1899, device='cuda:4') 2184
tensor([[728.,   2.,   6.],
        [  4., 672.,  50.],
        [ 35., 188., 499.]])
tensor(1382.5895, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1971, device='cuda:4') 2184
tensor([[727.,   4.,   6.],
        [  4., 691.,  30.],
        [ 13., 156., 553.]])
tensor(1377.6195, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1940, device='cuda:4') 2184
tensor([[711.,   2.,  24.],
        [  4., 675.,  46.],
        [ 11., 157., 554.]])
tensor(1378.7896, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1933, device='cuda:4') 2184
tensor([[711.,   4.,  22.],
        [  5., 677.,  44.],
        [ 10.,

tensor(1918, device='cuda:4') 2184
tensor([[668.,  17.,  52.],
        [  4., 679.,  42.],
        [  7., 144., 571.]])
tensor(1391.1132, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1932, device='cuda:4') 2184
tensor([[720.,   4.,  13.],
        [  3., 642.,  81.],
        [ 13., 138., 570.]])
tensor(1350.6699, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1985, device='cuda:4') 2184
tensor([[708.,   9.,  20.],
        [  4., 683.,  38.],
        [ 10., 118., 594.]])
tensor(1357.3922, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1984, device='cuda:4') 2184
tensor([[712.,  10.,  15.],
        [  4., 692.,  30.],
        [ 13., 128., 580.]])
tensor(1358.4840, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1976, device='cuda:4') 2184
tensor([[713.,   3.,  20.],
        [  4., 681.,  41.],
        [ 15., 125., 582.]])
tensor(1365.1438, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1965, device='cuda:4') 2184
tensor([[712.,   3.,  21.],
        [  4., 678.,  44.],
        [ 11.,

tensor(1962, device='cuda:4') 2184
tensor([[694.,  42.,   1.],
        [  4., 706.,  15.],
        [ 14., 146., 562.]])
tensor(1353.1444, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2013, device='cuda:4') 2184
tensor([[700.,  36.,   0.],
        [  4., 700.,  22.],
        [ 12.,  97., 613.]])
tensor(1347.7004, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2003, device='cuda:4') 2184
tensor([[701.,  34.,   2.],
        [  4., 709.,  12.],
        [ 11., 118., 593.]])
tensor(1347.6364, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1974, device='cuda:4') 2184
tensor([[693.,  40.,   4.],
        [  4., 699.,  23.],
        [ 12., 127., 582.]])
tensor(1356.9946, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1954, device='cuda:4') 2184
tensor([[682.,  38.,  17.],
        [  4., 691.,  30.],
        [ 12., 129., 581.]])
tensor(1375.0934, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1958, device='cuda:4') 2184
tensor([[668.,  41.,  28.],
        [  4., 694.,  27.],
        [  8.,

tensor(1913, device='cuda:4') 2184
tensor([[682.,   8.,  47.],
        [  3., 643.,  80.],
        [  6., 127., 588.]])
tensor(1377.2609, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1981, device='cuda:4') 2184
tensor([[697.,  13.,  27.],
        [  2., 679.,  45.],
        [  3., 113., 605.]])
tensor(1357.7140, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1988, device='cuda:4') 2184
tensor([[713.,  10.,  14.],
        [  2., 693.,  31.],
        [  7., 132., 582.]])
tensor(1357.4700, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1974, device='cuda:4') 2184
tensor([[706.,   7.,  24.],
        [  2., 693.,  31.],
        [  4., 142., 575.]])
tensor(1338.4913, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1982, device='cuda:4') 2184
tensor([[705.,   7.,  25.],
        [  2., 704.,  20.],
        [  6., 142., 573.]])
tensor(1347.0682, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1922, device='cuda:4') 2184
tensor([[702.,   7.,  27.],
        [  2., 631.,  93.],
        [ 17.,

tensor(1975, device='cuda:4') 2184
tensor([[716.,   7.,  14.],
        [  3., 668.,  54.],
        [ 11., 120., 591.]])
tensor(1403.2097, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1857, device='cuda:4') 2184
tensor([[661.,   8.,  68.],
        [  5., 621., 100.],
        [ 10., 136., 575.]])
tensor(1412.1923, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1915, device='cuda:4') 2184
tensor([[685.,  22.,  30.],
        [  4., 668.,  53.],
        [ 12., 148., 562.]])
tensor(1354.7424, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1955, device='cuda:4') 2184
tensor([[707.,  14.,  16.],
        [  4., 679.,  42.],
        [ 11., 142., 569.]])
tensor(1350.8202, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1953, device='cuda:4') 2184
tensor([[721.,   9.,   7.],
        [  4., 684.,  38.],
        [ 14., 159., 548.]])
tensor(1336.1079, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2012, device='cuda:4') 2184
tensor([[711.,   9.,  16.],
        [  4., 694.,  28.],
        [ 14.,

tensor(1993, device='cuda:4') 2184
tensor([[689.,  29.,  18.],
        [  4., 697.,  25.],
        [  3., 112., 607.]])
tensor(1346.6526, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1988, device='cuda:4') 2184
tensor([[707.,  20.,  10.],
        [  6., 701.,  18.],
        [  4., 138., 580.]])
tensor(1343.7987, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1968, device='cuda:4') 2184
tensor([[705.,  22.,  10.],
        [  6., 683.,  36.],
        [  4., 138., 580.]])
tensor(1360.1244, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1957, device='cuda:4') 2184
tensor([[678.,  33.,  26.],
        [  6., 689.,  31.],
        [ 10., 121., 590.]])
tensor(1344.4220, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1969, device='cuda:4') 2184
tensor([[700.,  26.,  11.],
        [  5., 687.,  34.],
        [ 14., 125., 582.]])
tensor(1337.5195, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1983, device='cuda:4') 2184
tensor([[701.,  26.,  10.],
        [  5., 699.,  22.],
        [  9.,

tensor(1341.1390, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1959, device='cuda:4') 2184
tensor([[699.,  10.,  27.],
        [  4., 676.,  46.],
        [ 15., 123., 584.]])
tensor(1341.7109, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1989, device='cuda:4') 2184
tensor([[708.,   9.,  19.],
        [  4., 696.,  26.],
        [ 10., 127., 585.]])
tensor(1339.0260, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1968, device='cuda:4') 2184
tensor([[706.,   7.,  24.],
        [  4., 697.,  24.],
        [  7., 150., 565.]])
tensor(1317.1801, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2015, device='cuda:4') 2184
tensor([[730.,   5.,   2.],
        [  3., 693.,  30.],
        [  9., 120., 592.]])
tensor(1310.4209, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2019, device='cuda:4') 2184
tensor([[721.,  14.,   1.],
        [  3., 693.,  30.],
        [  4., 113., 605.]])
tensor(1315.1084, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2007, device='cuda:4') 2184
tensor([[73

tensor(1338.2344, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2011, device='cuda:4') 2184
tensor([[716.,   7.,  14.],
        [  5., 696.,  25.],
        [  8., 114., 599.]])
tensor(1336.9120, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1990, device='cuda:4') 2184
tensor([[711.,  10.,  16.],
        [  4., 690.,  32.],
        [ 10., 122., 589.]])
tensor(1339.8508, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2007, device='cuda:4') 2184
tensor([[710.,  11.,  16.],
        [  4., 699.,  22.],
        [  8., 116., 598.]])
tensor(1338.6411, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2015, device='cuda:4') 2184
tensor([[708.,   6.,  23.],
        [  4., 694.,  27.],
        [  8., 101., 613.]])
tensor(1327.2404, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1975, device='cuda:4') 2184
tensor([[707.,  14.,  15.],
        [  4., 695.,  27.],
        [  7., 142., 573.]])
tensor(1333.7626, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2007, device='cuda:4') 2184
tensor([[70

tensor(1354.1726, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1989, device='cuda:4') 2184
tensor([[690.,  32.,  14.],
        [  4., 689.,  33.],
        [  3., 109., 610.]])
tensor(1359.0828, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1948, device='cuda:4') 2184
tensor([[668.,  33.,  36.],
        [  4., 686.,  35.],
        [  7., 121., 594.]])
tensor(1363.1510, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1964, device='cuda:4') 2184
tensor([[656.,  35.,  46.],
        [  4., 701.,  21.],
        [  3., 111., 607.]])
tensor(1384.1571, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1930, device='cuda:4') 2184
tensor([[643.,  33.,  61.],
        [  4., 681.,  41.],
        [  2., 113., 606.]])
tensor(1421.3960, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1905, device='cuda:4') 2184
tensor([[622.,  46.,  69.],
        [  4., 676.,  45.],
        [  5., 110., 607.]])
tensor(1415.5847, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1938, device='cuda:4') 2184
tensor([[64

tensor(1324.3142, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2021, device='cuda:4') 2184
tensor([[706.,   2.,  29.],
        [  4., 714.,   8.],
        [  7., 113., 601.]])
tensor(1327.2006, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1998, device='cuda:4') 2184
tensor([[689.,  10.,  37.],
        [  4., 711.,  11.],
        [  7., 117., 598.]])
tensor(1326.2933, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2022, device='cuda:4') 2184
tensor([[703.,   5.,  28.],
        [  4., 708.,  14.],
        [  9., 102., 611.]])
tensor(1327.1078, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2013, device='cuda:4') 2184
tensor([[696.,  11.,  30.],
        [  4., 711.,  10.],
        [  9., 107., 606.]])
tensor(1330.6456, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1965, device='cuda:4') 2184
tensor([[696.,  13.,  27.],
        [  6., 702.,  18.],
        [  9., 146., 567.]])
tensor(1357.4293, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1981, device='cuda:4') 2184
tensor([[69

tensor(1359.7172, device='cuda:4', grad_fn=<AddBackward0>)
tensor(1996, device='cuda:4') 2184
tensor([[687.,  15.,  35.],
        [  6., 711.,   8.],
        [  6., 118., 598.]])
tensor(1345.2501, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2016, device='cuda:4') 2184
tensor([[677.,  23.,  36.],
        [  4., 716.,   6.],
        [  4.,  95., 623.]])
tensor(1329.7607, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2032, device='cuda:4') 2184
tensor([[697.,  15.,  25.],
        [  5., 712.,   8.],
        [  5.,  94., 623.]])
tensor(1319.2883, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2031, device='cuda:4') 2184
tensor([[703.,  17.,  17.],
        [  5., 708.,  13.],
        [ 11.,  90., 620.]])
tensor(1334.4392, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2030, device='cuda:4') 2184
tensor([[709.,  18.,  10.],
        [  4., 712.,   9.],
        [  7., 106., 609.]])
tensor(1307.2070, device='cuda:4', grad_fn=<AddBackward0>)
tensor(2062, device='cuda:4') 2184
tensor([[72

KeyboardInterrupt: 

In [1]:
torch.save(model1.state_dict(), '3AnkitBiLSTMBCLL1.pt')
torch.save(model2.state_dict(), '3AnkitBiLSTMBCLL2.pt')
torch.save(model3.state_dict(), '3AnkitBiLSTMBCLL3.pt')

NameError: name 'torch' is not defined

In [ ]:
tensor(1436, device='cuda:4') 2184
tensor([[707.,   3.,  27.],
        [  7., 120., 598.],
        [ 26.,  87., 609.]])   #66percent - (1)

tensor(1998, device='cuda:4') 2184
tensor([[701.,  21.,  15.],
        [  4., 685.,  36.],
        [  5., 105., 612.]])   #91.4percent - (2)


